[package]
name = "webapi"
version = "0.1.0"
edition = "2021"
authors = ["nurakmaljalil91 <nurakmaljalil91@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"